######################################################################
# Automatically generated by qmake (2.01a) ?? 2? 18 13:08:34 2018
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
FORMS += gotocelldialog.ui
SOURCES += main.cpp
